- name: Install Docker Prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Add Docker GPG Key
  ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Get Architecture
  ansible.builtin.shell: dpkg --print-architecture
  register: architecture

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch={{ architecture.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian buster stable
    filename: docker
    state: present

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes
    state: present

- name: Install Docker-Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Create /etc/docker
  ansible.builtin.file:
    state: directory
    path: /etc/docker
    mode: '0755'
    owner: root
    group: root

- name: Set Max Log Size
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: '0700'
