- name: Check user in sudo group
  ansible.builtin.getent:
    database: group
    key: sudo
    split: ":"

- name: Check sudo command exists
  ansible.builtin.stat:
    path: /usr/bin/sudo
  register: sudofile

- name: Select become method sudo
  ansible.builtin.set_fact:
    use_become_method: sudo
  when: ansible_facts.getent_group.sudo[2] is search(ansible_user) and sudofile.stat.exists

- name: Select become method su
  ansible.builtin.set_fact:
    use_become_method: su
  when: use_become_method is undefined
