- name: Install Basics
  ansible.builtin.apt:
    update_cache: yes
    name:
      - sudo
      - zsh
      - iptables-persistent
      - vim-gtk3
      - net-tools
      - netcat-openbsd
      - spice-vdagent
      - qemu-guest-agent
      - sshpass
      - tmux
      - gcc
      - binutils-doc
      - make
      - autoconf
      - automake
      - flex
      - bison
      - gdb
      - git
      - sshfs
      - unattended-upgrades
      - tcpdump
      - dma
      - bsd-mailx
      - dnsutils
      - python-is-python3

- name: Add user to sudo, set shell to zsh, generate SSH key
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh
    groups: sudo
    append: yes
    generate_ssh_key: yes

- name: Set root shell to zsh, generate SSH key
  ansible.builtin.user:
    name: root
    shell: /usr/bin/zsh
    generate_ssh_key: yes

- name: Setup Unattended Upgrades - Debconf Selections
  ansible.builtin.shell: echo unattended-upgrades unattended-upgrades/enable_auto_updates boolean true | debconf-set-selections
  args:
    creates: /etc/apt/apt.conf.d/20auto-upgrades

- name: Setup Unattended Upgrades - Run dpkg-reconfigure
  ansible.builtin.shell: /usr/sbin/dpkg-reconfigure -f noninteractive unattended-upgrades
  args:
    creates: /etc/apt/apt.conf.d/20auto-upgrades

- name: Setup Unattended Upgrades - Email Root
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: 'Unattended-Upgrade::Mail '
    line: 'Unattended-Upgrade::Mail "root";'

- name: Setup Unattended Upgrades - Email On Error
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: 'Unattended-Upgrade::MailReport '
    line: 'Unattended-Upgrade::MailReport "only-on-error";'

- name: Setup Dragonfly Mail Agent - Aliases
  ansible.builtin.template:
    src: aliases
    dest: /etc/aliases
    owner: root
    group: root
    mode: '0644'

- name: Setup Dragonfly Mail Agent - Auth
  ansible.builtin.template:
    src: auth.conf
    dest: /etc/dma/auth.conf
    owner: root
    group: mail
    mode: '0640'

- name: Setup Dragonfly Mail Agent - Conf
  ansible.builtin.template:
    src: dma.conf
    dest: /etc/dma/dma.conf
    owner: root
    group: mail
    mode: '0640'
