- name: Install k3d
  ansible.builtin.shell: curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
  args:
    creates: /usr/local/bin/k3d

- name: Download kubectl
  ansible.builtin.shell: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o kubectl
  args:
    creates: /usr/local/bin/kubectl

- name: Install kubectl
  ansible.builtin.shell: sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  args:
    creates: /usr/local/bin/kubectl

- name: Remove downloaded kubectl
  ansible.builtin.shell: rm kubectl
  args:
    removes: kubectl

- name: Download kustomize
  ansible.builtin.shell: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
  args:
    creates: /usr/local/bin/kustomize

- name: Install kustomize
  ansible.builtin.shell: sudo install -o root -g root -m 0755 kustomize /usr/local/bin/kustomize
  args:
    creates: /usr/local/bin/kustomize

- name: Install helm
  ansible.builtin.shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm

- name: Set vm.max_map_count
  ansible.builtin.template:
    src: vm-max_map_count.conf
    dest: /etc/sysctl.d/vm-max_map_count.conf
    mode: '0644'
  register: vm_max_map

- name: Set fs.file-max
  ansible.builtin.template:
    src: fs-file-max.conf
    dest: /etc/sysctl.d/fs-file-max.conf
    mode: '0644'
  register: fs_file_max

- name: Load updated configuration
  ansible.builtin.shell: sysctl --load --system
  when: vm_max_map.changed or fs_file_max.changed

- name: Setup required istio modules
  ansible.builtin.template:
    src: istio_modules
    dest: /etc/modules-load.d/istio_modules.conf
    mode: '0644'
  register: istio_modules

- name: Install istio modules now
  ansible.builtin.shell: modprobe xt_REDIRECT && modprobe xt_owner && modprobe xt_statistic
  when: istio_modules.changed
